window.SAMPLE_DATA = {
  projects: [
    {
      project_id: "P-2026-001",
      project_name: "〇〇様邸 新築工事",
      customer_name: "〇〇様",
      site_address: "大阪府大阪市北区 サンプル住所",
      project_type: "新築",
      planned_start: "2026-05-10",
      planned_end: "2026-07-05",
      status: "予定",
      project_folder: "pre-contract",
      deleted_at: "",
      previous_folder: "",
      manager: "藤井",
      memo: "初期サンプル。足場あり・標準工程。",
    },
    {
      project_id: "P-2026-002",
      project_name: "△△店舗 改装工事",
      customer_name: "△△店舗",
      site_address: "大阪府大阪市中央区 サンプル住所",
      project_type: "改装",
      planned_start: "2026-05-18",
      planned_end: "2026-06-18",
      status: "進行中",
      project_folder: "active",
      deleted_at: "",
      previous_folder: "",
      manager: "山田",
      memo: "店舗改装。夜間作業の可能性あり。",
    },
    {
      project_id: "P-2026-003",
      project_name: "□□マンション 内装工事",
      customer_name: "□□管理組合",
      site_address: "兵庫県尼崎市 サンプル住所",
      project_type: "内装",
      planned_start: "2026-06-01",
      planned_end: "2026-06-28",
      status: "予定",
      project_folder: "pre-contract",
      deleted_at: "",
      previous_folder: "",
      manager: "佐藤",
      memo: "内装中心。足場なし想定。",
    },
  ],
  tasks: [
    {
      id: "T-001",
      project_id: "P-2026-001",
      name: "現地調査",
      category: "事前準備",
      start: "2026-05-10",
      end: "2026-05-11",
      progress: 100,
      contractor: "社内",
      status: "完了",
      dependencies: "",
      memo: "敷地・搬入経路確認",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-002",
      project_id: "P-2026-001",
      name: "図面確認・材料手配",
      category: "事前準備",
      start: "2026-05-11",
      end: "2026-05-15",
      progress: 70,
      contractor: "社内",
      status: "進行中",
      dependencies: "T-001",
      memo: "建具・設備品番確認",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-003",
      project_id: "P-2026-001",
      name: "足場設置",
      category: "仮設",
      start: "2026-05-16",
      end: "2026-05-17",
      progress: 0,
      contractor: "足場業者A",
      status: "未着手",
      dependencies: "T-002",
      memo: "道路使用確認",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-004",
      project_id: "P-2026-001",
      name: "基礎工事",
      category: "大工",
      start: "2026-05-18",
      end: "2026-05-28",
      progress: 0,
      contractor: "基礎業者B",
      status: "未着手",
      dependencies: "T-003",
      memo: "天候で前後の可能性あり",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-005",
      project_id: "P-2026-001",
      name: "木工事",
      category: "大工",
      start: "2026-05-29",
      end: "2026-06-15",
      progress: 0,
      contractor: "大工チームC",
      status: "未着手",
      dependencies: "T-004",
      memo: "上棟含む",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-006",
      project_id: "P-2026-001",
      name: "電気工事",
      category: "電気",
      start: "2026-06-08",
      end: "2026-06-18",
      progress: 0,
      contractor: "電気業者D",
      status: "未着手",
      dependencies: "T-005",
      memo: "木工事と一部重なりあり",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-007",
      project_id: "P-2026-001",
      name: "水道工事",
      category: "水道",
      start: "2026-06-10",
      end: "2026-06-20",
      progress: 0,
      contractor: "設備業者E",
      status: "未着手",
      dependencies: "T-005",
      memo: "電気工事と同時期",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-008",
      project_id: "P-2026-001",
      name: "クロス工事",
      category: "内装",
      start: "2026-06-21",
      end: "2026-06-27",
      progress: 0,
      contractor: "内装業者F",
      status: "未着手",
      dependencies: "T-006,T-007",
      memo: "面積に応じて工期調整",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-009",
      project_id: "P-2026-001",
      name: "設備取付",
      category: "設備",
      start: "2026-06-25",
      end: "2026-07-01",
      progress: 0,
      contractor: "設備業者E",
      status: "未着手",
      dependencies: "T-008",
      memo: "クロス後半と一部重なり",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-010",
      project_id: "P-2026-001",
      name: "美装・施主確認",
      category: "確認",
      start: "2026-07-02",
      end: "2026-07-05",
      progress: 0,
      contractor: "社内",
      status: "未着手",
      dependencies: "T-009",
      memo: "最終確認・是正対応含む",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-101",
      project_id: "P-2026-002",
      name: "現地調査",
      category: "事前準備",
      start: "2026-05-18",
      end: "2026-05-18",
      progress: 100,
      contractor: "社内",
      status: "完了",
      dependencies: "",
      memo: "営業中動線確認",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-102",
      project_id: "P-2026-002",
      name: "解体工事",
      category: "解体",
      start: "2026-05-20",
      end: "2026-05-24",
      progress: 40,
      contractor: "解体業者G",
      status: "進行中",
      dependencies: "T-101",
      memo: "騒音時間に注意",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-103",
      project_id: "P-2026-002",
      name: "電気・水道先行配線",
      category: "設備",
      start: "2026-05-24",
      end: "2026-05-30",
      progress: 10,
      contractor: "設備業者E",
      status: "進行中",
      dependencies: "T-102",
      memo: "厨房設備位置確認",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-104",
      project_id: "P-2026-002",
      name: "内装下地",
      category: "内装",
      start: "2026-05-31",
      end: "2026-06-08",
      progress: 0,
      contractor: "内装業者F",
      status: "未着手",
      dependencies: "T-103",
      memo: "造作カウンター含む",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-105",
      project_id: "P-2026-002",
      name: "クロス・床仕上げ",
      category: "内装",
      start: "2026-06-09",
      end: "2026-06-14",
      progress: 0,
      contractor: "内装業者F",
      status: "未着手",
      dependencies: "T-104",
      memo: "夜間施工の可能性あり",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-106",
      project_id: "P-2026-002",
      name: "引き渡し前確認",
      category: "確認",
      start: "2026-06-15",
      end: "2026-06-18",
      progress: 0,
      contractor: "社内",
      status: "未着手",
      dependencies: "T-105",
      memo: "是正対応含む",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-201",
      project_id: "P-2026-003",
      name: "現地調査・管理組合確認",
      category: "事前準備",
      start: "2026-06-01",
      end: "2026-06-03",
      progress: 0,
      contractor: "社内",
      status: "未着手",
      dependencies: "",
      memo: "搬入・作業時間確認",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-202",
      project_id: "P-2026-003",
      name: "養生・解体",
      category: "解体",
      start: "2026-06-04",
      end: "2026-06-08",
      progress: 0,
      contractor: "解体業者G",
      status: "未着手",
      dependencies: "T-201",
      memo: "共用部養生必須",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-203",
      project_id: "P-2026-003",
      name: "内装工事",
      category: "内装",
      start: "2026-06-09",
      end: "2026-06-20",
      progress: 0,
      contractor: "内装業者F",
      status: "未着手",
      dependencies: "T-202",
      memo: "床・壁・天井",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-204",
      project_id: "P-2026-003",
      name: "設備取付・美装",
      category: "設備",
      start: "2026-06-21",
      end: "2026-06-26",
      progress: 0,
      contractor: "設備業者E",
      status: "未着手",
      dependencies: "T-203",
      memo: "同時に美装段取り",
      source: "sample",
      is_manual_edited: false,
    },
    {
      id: "T-205",
      project_id: "P-2026-003",
      name: "確認・引き渡し",
      category: "確認",
      start: "2026-06-27",
      end: "2026-06-28",
      progress: 0,
      contractor: "社内",
      status: "未着手",
      dependencies: "T-204",
      memo: "写真提出",
      source: "sample",
      is_manual_edited: false,
    },
  ],
  templateTasks: [
    { name: "現地調査", category: "事前準備", duration: 1, offset: 0, contractor: "社内" },
    { name: "図面確認", category: "事前準備", duration: 2, offset: 1, contractor: "社内" },
    { name: "材料手配", category: "事前準備", duration: 3, offset: 3, contractor: "社内" },
    { name: "足場設置", category: "仮設", duration: 1, offset: 6, contractor: "足場業者" },
    { name: "解体工事", category: "解体", duration: 4, offset: 7, contractor: "解体業者" },
    { name: "木工事", category: "大工", duration: 10, offset: 11, contractor: "大工" },
    { name: "電気工事", category: "電気", duration: 5, offset: 17, contractor: "電気業者" },
    { name: "水道工事", category: "水道", duration: 5, offset: 18, contractor: "水道業者" },
    { name: "クロス工事", category: "内装", duration: 5, offset: 24, contractor: "内装業者" },
    { name: "設備工事", category: "設備", duration: 4, offset: 29, contractor: "設備業者" },
    { name: "美装・施主確認", category: "確認", duration: 3, offset: 33, contractor: "社内" },
  ],
};
